// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXhgrs0MHsk9M_m0kzjGr0_oQ4UW39GQ',
    appId: '1:833929711528:web:575f6733992305b800179d',
    messagingSenderId: '833929711528',
    projectId: 'pinpoint-7b1f0',
    authDomain: 'pinpoint-7b1f0.firebaseapp.com',
    storageBucket: 'pinpoint-7b1f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVjeSWgdMNhdHwXYfX0duZw4Vkk_3u8g',
    appId: '1:833929711528:android:255b06a17389c56d00179d',
    messagingSenderId: '833929711528',
    projectId: 'pinpoint-7b1f0',
    storageBucket: 'pinpoint-7b1f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nyh1v--BrRktxgabALrjR_6tnd5OMGE',
    appId: '1:833929711528:ios:0d5659cdd00863fe00179d',
    messagingSenderId: '833929711528',
    projectId: 'pinpoint-7b1f0',
    storageBucket: 'pinpoint-7b1f0.appspot.com',
    iosClientId: '833929711528-2htmvv4ii7drdajd5e8kcqr1uocardg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nyh1v--BrRktxgabALrjR_6tnd5OMGE',
    appId: '1:833929711528:ios:0d5659cdd00863fe00179d',
    messagingSenderId: '833929711528',
    projectId: 'pinpoint-7b1f0',
    storageBucket: 'pinpoint-7b1f0.appspot.com',
    iosClientId: '833929711528-2htmvv4ii7drdajd5e8kcqr1uocardg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinpoint',
  );
}
